# Welcome to Jekyll!
#

# Site settings
title: Forge
description: |
  F# CLI tool for project,
  file, and solution management
owner: Krzysztof Cieslak, Reid Evans, Jared Haster # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: krzysztof_cieslak@windowslive.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://forge.run" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/k_cieslak
  github: https://github.com/Krzysztof-Cieslak
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: krzysztof_cieslak@windowslive.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
